Added action to set a policy by name or ID
deep-security/ansible pull request #10
Opened 2018-05-29 20:18 UTC by PhilippBehmer

2018-06-07 09:34 UTC, harrisonchen201703 requested changes

2018-06-07 09:34 UTC, harrisonchen201703 commented on tasks/manage.yml
> +    dsa_control_argument: "-m 'policyid:{{ policy }}'"
you may want to use policy_id as parameter instead of using policy.

2018-06-07 09:34 UTC, harrisonchen201703 commented on tasks/manage.yml
> +    dsa_control_argument: "-m 'policy:{{ policy }}'"
You may want to use "policy_name" instead of "policy" to make the purpose of this parameter more clear.

2018-06-07 09:34 UTC, harrisonchen201703 commented on tasks/manage.yml
> +  when: action == 'set-policy'
Maybe it's better to use "set-policy-by-name"?

2018-06-07 09:34 UTC, harrisonchen201703 commented on tasks/manage.yml
> +  when: action == 'set-policyid'
Maybe it's better to use "set-policy-by-id"?

2018-06-07 14:29 UTC, ChristinaSmith123 commented on README.md
> +The "manage" task will help users operate the Deep Security Agent without logining into the Deep Security Manager. All of the available actions assume that the Deep Security Agent is installed and ac
logining into -> logging in to (typo and you need a space between 'in' and 'to'

2018-06-08 07:48 UTC, PhilippBehmer commented
@harrisonchen201703 I implemented your suggested changes and updated the readme. A test run in my environment was successful.

2018-06-08 09:36 UTC, harrisonchen201703 commented
Looks great, thanks @PhilippBehmer for your change.

2018-06-08 09:36 UTC, harrisonchen201703 approved these changes

2018-06-08 09:41 UTC, merged