Task/add instllation guide for ansible galaxy
deep-security/ansible pull request #21
Opened 2018-08-08 10:12 UTC by harrisonchen201703

- Add usage in README.md for both download from github and Ansible-Galaxy

2018-08-09 14:21 UTC, ChristinaSmith123 requested changes

2018-08-09 14:21 UTC, ChristinaSmith123 commented on README.md
> +Currently we have provided 2 ways to retrive this role:
2 -> two

2018-08-09 14:21 UTC, ChristinaSmith123 commented on README.md
> +Currently we have provided 2 ways to retrive this role:
retrive -> retrieve

2018-08-09 14:21 UTC, ChristinaSmith123 commented on README.md
> + * From Ansible-Galaxy
From Ansible-Galaxy -> Download from

2018-08-09 14:21 UTC, ChristinaSmith123 commented on README.md
> +### Download From Ansible-Galaxy
Download From Ansible-Galaxy -> Download from Ansible-Galaxy.
Please use 'sentence case' for all headings. Example:

Correct: Download your file now
Incorrect: Download Your File Now

Even though you are using sentence case, remember to preserve capital letters on things that require a capital letter.
Correct: Download the Agent now
Incorrect: Download the agent now

2018-08-09 14:21 UTC, ChristinaSmith123 commented on README.md
> +### Download From this repo
Download From -> Download from

2018-08-10 06:19 UTC, lovemew67 commented on README.md
> +        │
MINOR: Remove redundant bar to see more compact.

2018-08-10 06:19 UTC, lovemew67 commented on README.md
> +        │
Ditto.

2018-08-10 06:20 UTC, lovemew67 requested changes
See comments

2018-08-13 05:57 UTC, lovemew67 commented on README.md
>   * Please visit our role in [ Ansible-Galaxy](https://galaxy.ansible.com/deep-security/deep-security-agent)
[Ansible-Galaxy]

2018-08-13 08:13 UTC, lovemew67 approved these changes

2018-08-13 08:15 UTC, harrisonchen201703 commented on README.md
> +### Download From Ansible-Galaxy
Thanks for reminding, i'll check with rest of the content.

2018-08-13 08:15 UTC, harrisonchen201703 commented on README.md
> +Currently we have provided 2 ways to retrive this role:
Thanks, will update in next commit.

2018-08-13 08:15 UTC, harrisonchen201703 commented on README.md
> + * From Ansible-Galaxy
Thanks, will update in next commit.

2018-08-13 08:15 UTC, harrisonchen201703 commented on README.md
> +        │
Thanks, will update in next commit.

2018-08-13 08:15 UTC, harrisonchen201703 commented on README.md
> +        │
Thanks, will update in next commit.

2018-08-13 13:53 UTC, ChristinaSmith123 commented on README.md
> +### Download from this repo
Sorry I didn't catch this but I think this should say 'Clone from this repo' so that it matches the wording at the top.

2018-08-14 13:53 UTC, ChristinaSmith123 reviewed
Looks good!

2018-08-15 14:01 UTC, ChristinaSmith123 approved these changes

2018-08-17 01:54 UTC, lovemew67 approved these changes

2018-08-20 05:34 UTC, merged